# These are supported funding model platforms
# Uncomment and fill in the ones that apply to your project

# github: [username]
# patreon: username
# open_collective: project-name
# ko_fi: username
# buy_me_a_coffee: username
# custom: ["https://your-link.com"]
