name: Plugin CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  plugin-ci:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: read
    uses: mpiton/vortex/.github/workflows/plugin-ci.yml@9b3b7b3b7956150f7475ab409bb0eed424573bae

  plugin-release:
    if: ${{ startsWith(github.ref, 'refs/tags/') && github.actor == github.repository_owner }}
    permissions:
      contents: write
    uses: mpiton/vortex/.github/workflows/plugin-release.yml@1b0cc276086cfc87165d63f8c5624fa3960ad2e9
