name: Plugin CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  plugin-ci:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: read
    uses: mpiton/vortex/.github/workflows/plugin-ci.yml@f63e53f866bbdf5e5e3e8f62a37f78e13cec5298

  plugin-release:
    if: ${{ startsWith(github.ref, 'refs/tags/') && github.actor == github.repository_owner }}
    permissions:
      contents: write
    uses: mpiton/vortex/.github/workflows/plugin-release.yml@d85baa93ac7905c5813095b2406f2a3642458356
